In [4]:
import pandas as pd
import requests
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [5]:
res=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=6b591f30e2e98b7babae6651a30b63e9&language=en-US&page=1')

In [6]:
df=pd.DataFrame(res.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [7]:
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,46.2770,8.700,30192
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,42.1371,8.700,22805
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,27.5151,8.572,13827
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,28.0741,8.600,17356
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,19.8707,8.600,9912

In [8]:
df =pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [9]:
# all_data = []

# for i in range(1, 542):
#     res = requests.get(f'https://api.themoviedb.org/3/movie/top_rated?api_key=6b591f30e2e98b7babae6651a30b63e9&language=en-US&page={i}')
    
#     temp_df = pd.DataFrame(res.json()['results'])[
#         ['id','title','overview','release_date','popularity','vote_average','vote_count']
#     ]
    
#     all_data.append(temp_df)

# # ek baar me combine karo
# df = pd.concat(all_data, ignore_index=True)

In [12]:
import pandas as pd
import requests
from concurrent.futures import ThreadPoolExecutor

API_KEY = "6b591f30e2e98b7babae6651a30b63e9"

def fetch_page(i):
    url = f'https://api.themoviedb.org/3/movie/top_rated?api_key={API_KEY}&language=en-US&page={i}'
    res = requests.get(url)
    data = res.json()
    
    if 'results' in data:
        return pd.DataFrame(data['results'])[
            ['id','title','overview','release_date','popularity','vote_average','vote_count']
        ]
    return pd.DataFrame()

# parallel execution
with ThreadPoolExecutor(max_workers=10) as executor:
    results = list(executor.map(fetch_page, range(1, 542)))

df = pd.concat(results, ignore_index=True)
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,46.2770,8.700,30192
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,42.1371,8.700,22805
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,27.5151,8.572,13827
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,28.0741,8.600,17356
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,19.8707,8.600,9912
...,...,...,...,...,...,...,...
9995,343173,The Rezort,"The ReZort, a post apocalyptic safari, offers ...",2015-06-15,1.2676,5.509,402
9996,46441,Mirrors 2,"When Max, who is recovering from a traumatic a...",2010-10-18,2.1118,5.509,437
9997,13160,Over Her Dead Body,"After his fiancée, Kate, dies in an accident o...",2008-02-01,1.7369,5.509,487
9998,12121,Made in America,A young black woman discovers that her father ...,1993-01-06,1.3281,5.500,386
9999,9271,Virtuosity,The Law Enforcement Technology Advancement Cen...,1995-08-04,3.3444,5.508,597

In [13]:
df.shape

(10000, 7)

In [14]:
df.to_csv("top_rated_movie.csv")